# Generated by Django 4.2.5 on 2023-11-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SieraApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
