# Generated by Django 4.2.5 on 2023-11-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SieraApp', '0006_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='carDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('capacity', models.CharField(blank=True, max_length=2, null=True)),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('engine', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('include', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SieraApp.location')),
            ],
        ),
    ]
