# Generated by Django 4.2.5 on 2023-11-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SieraApp', '0007_cardetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetail',
            name='location',
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
