# Generated by Django 4.2.5 on 2023-12-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SieraApp', '0010_remove_car_capacity_alter_car_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
